version: "3"

services:
  telegram_bot:
    build:
      context: ./telegram_bot
      dockerfile: dockerfile
    networks:
      - cv_code
    ports:
      - 7653:7653
    expose:
      - 7653
    links:
      - postgre_db
    depends_on:
      - postgre_db

  web_app:
    build:
      context: ./web_app
      dockerfile: dockerfile
    networks:
      - cv_code
    expose:
      - 7654
    ports:
      - 7654:7654
    links:
      - postgre_db
    depends_on:
      - postgre_db

  postgre_db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: cvcode
      POSTGRES_PASSWORD: cvcode
      POSTGRES_DB: cvcode_database
    networks:
      - cvcode
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  cvcode:
    external: true

volumes:
  db-data:
