version: "3"

services:
  telegram_bot:
    build:
      context: ./telegram_bot
      dockerfile: dockerfile
    command:
      - bot_main.py
    networks:
      - cv_code
    ports:
      - 7653:7653
    expose:
      - 7653
    links:
      - postgre_db
    depends_on:
      - postgre_db
      - db_create

  db_init:
    build:
      context: ./web_app
      dockerfile: dockerfile
    command:
      - init_db.py
    networks:
      - cv_code
    links:
      - postgre_db
    depends_on:
      - postgre_db
  db_create:
    build:
      context: ./telegram_bot
      dockerfile: dockerfile
    command:
      - create_data_base.py
    networks:
      - cv_code
    links:
      - postgre_db
    depends_on:
      - postgre_db
  web_app:
    build:
      context: ./web_app
      dockerfile: dockerfile
    command:
      - app.py
    networks:
      - cv_code
    expose:
      - 7654
    ports:
      - 7654:7654
    links:
      - postgre_db
    depends_on:
      - postgre_db

  postgre_db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: cvcode
      POSTGRES_PASSWORD: cvcode
      POSTGRES_DB: cvcode_database
    networks:
      - cv_code
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  cv_code:
    external: true

volumes:
  db-data:
