FROM python:3.9.15-alpine3.15

WORKDIR /telegram_bot
COPY . .

RUN pip3 install -r requirements.txt

EXPOSE 7653

RUN python3 create_data_base.py

ENTRYPOINT ["python3"]
CMD ["database_work.py"]
CMD ["bot_main.py"]